### ISSUE TITLE
Does not compile with latest bcc

### ISSUE THREAD

**Issue by noroads2015** [bmx-ng/mky.mod#3]
mky.mod does not compile correctly with the latest bcc.  Get **Compile Error: Field TTexture._width:Int is private.
[C:/BlitzMaxNG/mod/mky.mod/mojo2.mod/graphics.bmx;1086;0]**
There are several errors like this.  Calling the appropriate getter functions (you need to add one to get the contents of _data field), or setting the fields to public will solve the problem.

**Comment by GWRon** [comment]
I am not sure about this (which is why I am writing this now).

My suggestion is to add a Getter for each private field which is required outside. As NG converts to C, GCC will inline these online-getters. So it should not cost that more than direct field access.

If so then Brucey would surely merge a Pull Request regarding that issue (aka your chance to help even more).

But as said..I am not totally sure about the calling costs (getter vs field)
